//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;

    public partial class Employee
    {
        public int empId { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string addressStreet { get; set; }
        public string addressCity { get; set; }
        public string addressZip { get; set; }
        public string emailOne { get; set; }
        public string emailTwo { get; set; }
        public byte[] photo { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string phone { get; set; }
    }
}
